Repository mendesmariosatech/mmtech, pull requests merged in 2024-10, with the labels that each got.

#34 add new product
  .husky/pre-commit
  packages/ui/.storybook/preview.ts
  packages/ui/.storybook/preview.tsx
  packages/ui/src/components/composition/CardRealEstate/CardRealEstate.stories.tsx
  packages/ui/src/components/composition/CardRealEstate/CardRealEstate.tsx
  packages/ui/src/components/composition/Cards/Card.stories.ts
  packages/ui/src/components/composition/Cards/Card.tsx
  packages/ui/src/components/composition/Cards/data.tsx
  packages/ui/src/components/composition/DashBoard/Dashboard.stories.tsx
  packages/ui/src/components/composition/DashBoard/Dashboard.tsx
  packages/ui/src/components/composition/Lists/CardsList.stories.tsx
  packages/ui/src/components/composition/Lists/CardsList.tsx
  packages/ui/src/components/composition/Lists/EmptyList.stories.tsx
  packages/ui/src/components/composition/Lists/EmptyList.tsx
  packages/ui/src/components/composition/Lists/ProductsList.stories.tsx
  packages/ui/src/components/composition/Lists/ProductsList.tsx
  packages/ui/src/components/composition/Voting/Voting.stories.tsx
  packages/ui/src/components/composition/Voting/Voting.tsx
  packages/ui/src/components/form-builder/ControlledForm.tsx
  packages/ui/src/components/form-builder/ControlledInput.tsx
  packages/ui/src/components/form-builder/Forms/AddProduct/ProductForm.stories.tsx
  packages/ui/src/components/form-builder/Forms/AddProduct/ProductForm.tsx
  packages/ui/src/components/form-builder/Forms/DatePicker/DatePicker.stories.tsx
  packages/ui/src/components/form-builder/Forms/DatePicker/DatePicker.tsx
  packages/ui/src/globals.css
Labels: in progress

#31 [Server] - Jest Tests
  .github/workflows/jest.yml
  package.json
  packages/hook-services/react-query/useLogin.ts
  packages/hook-services/react-query/useRegister.tsx
  packages/server/.gitignore
  packages/server/README.md
  packages/server/jest.config.js
  packages/server/migrations/0000_nebulous_lilandra.sql
  packages/server/migrations/meta/0000_snapshot.json
  packages/server/migrations/meta/_journal.json
  packages/server/package.json
  packages/server/src/drizzle/schema.ts
  packages/server/src/env/cookies.ts
  packages/server/src/index.ts
  packages/server/src/middleware/authentication.ts
  packages/server/src/routes/auth/auth.test.ts
  packages/server/src/routes/auth/auth.ts
  packages/server/src/routes/auth/handlers/auth.dto.ts
  packages/server/src/routes/auth/handlers/client.dto.ts
  packages/server/src/routes/auth/handlers/findUser.ts
  packages/server/src/routes/auth/handlers/index.ts
  packages/server/src/routes/auth/register.ts
  packages/server/src/routes/secret/routeTest.ts
  packages/server/src/routes/tests/setup.ts
  packages/server/src/utils/bcrypt.ts
  packages/server/tsconfig.json
  packages/ui/src/components/form-builder/Forms/AddProduct/ProductForm.tsx
  packages/ui/src/components/form-builder/Forms/DatePicker/DatePicker.tsx
  packages/ui/src/components/form-builder/Forms/Login/LoginForm.tsx
  packages/ui/src/components/form-builder/Forms/Register/RegisterForm.tsx
  packages/ui/src/domains/Marketing/LandingPage/Header.tsx
  packages/zod-types/domains/auth/common.ts
  packages/zod-types/domains/auth/loginFields.ts
  packages/zod-types/domains/auth/registerFields.ts
  yarn.lock
Labels: ready for review

#37 Silas/UI sidebar
  packages/data-testing/DashBoardData.ts
  packages/data-testing/Routes.ts
  packages/data-testing/TooltipData.ts
  packages/data-testing/package.json
  packages/ui/package.json
  packages/ui/src/components/composition/DashBoard/Dashboard.stories.tsx
  packages/ui/src/components/composition/DashBoard/Dashboard.tsx
  packages/ui/src/components/iconData/IconData.tsx
  packages/ui/src/components/linkFormer/LinkFormer.stories.ts
  packages/ui/src/components/linkFormer/LinkFormer.tsx
  packages/ui/src/components/sheetFormer/SheetFormer.stories.ts
  packages/ui/src/components/sheetFormer/SheetFormer.tsx
  packages/ui/src/components/sideBar-builder/SideBarStatic.stories.ts
  packages/ui/src/components/sideBar-builder/SideBarStaticFormer.tsx
  packages/ui/src/components/toolTipButton/ToolTip.stories.ts
  packages/ui/src/components/toolTipButton/ToolTipBuilder.tsx
Labels: ready for review

#40 Dev to Release branch
  packages/data-testing/DashBoardData.ts
  packages/data-testing/Routes.ts
  packages/data-testing/TooltipData.ts
  packages/data-testing/package.json
  packages/ui/package.json
  packages/ui/src/components/composition/DashBoard/Dashboard.stories.tsx
  packages/ui/src/components/composition/DashBoard/Dashboard.tsx
  packages/ui/src/components/iconData/IconData.tsx
  packages/ui/src/components/linkFormer/LinkFormer.stories.ts
  packages/ui/src/components/linkFormer/LinkFormer.tsx
  packages/ui/src/components/sheetFormer/SheetFormer.stories.ts
  packages/ui/src/components/sheetFormer/SheetFormer.tsx
  packages/ui/src/components/sideBar-builder/SideBarStatic.stories.ts
  packages/ui/src/components/sideBar-builder/SideBarStaticFormer.tsx
  packages/ui/src/components/toolTipButton/ToolTip.stories.ts
  packages/ui/src/components/toolTipButton/ToolTipBuilder.tsx
Labels: ready for review

#42 Connect login and signup hooks with UI - Part 1
  apps/docs/app/client/dashboard/page.tsx
  apps/docs/app/layout.tsx
  apps/docs/public/favicon.ico
  packages/data-testing/Routes.ts
  packages/data-testing/TooltipData.ts
  packages/hook-services/package.json
  packages/hook-services/react-query/useLogin.ts
  packages/hook-services/react-query/useRegister.tsx
  packages/ui/.storybook/preview.tsx
  packages/ui/public/marketing/landingPage/hero.svg
  packages/ui/public/marketing/landingPage/section.svg
  packages/ui/src/components/linkFormer/LinkFormer.tsx
  packages/ui/src/components/ui/sonner.tsx
  packages/ui/src/domains/Auth/Login/LoginPage.stories.ts
  packages/ui/src/domains/Auth/Login/LoginPage.tsx
  packages/ui/src/domains/Auth/Register/RegisterFormWithHook.tsx
  packages/ui/src/domains/Auth/Register/RegisterPage.stories.ts
  packages/ui/src/domains/Auth/Register/RegisterPage.tsx
  packages/ui/src/domains/Marketing/Dashboard/Dashboard.stories.tsx
  packages/ui/src/domains/Marketing/Dashboard/Dashboard.tsx
  packages/ui/src/domains/Marketing/LandingPage/Header.tsx
  yarn.lock
Labels: ready for review

#44 Block user from accessing private routes - Part 2
  apps/docs/app/api/[[...route]]/route.ts
  apps/docs/middleware.ts
  packages/hook-services/react-query/index.ts
  packages/hook-services/react-query/useLogout.ts
  packages/server/src/routes/auth/auth.ts
  packages/ui/src/domains/Marketing/Dashboard/Dashboard.tsx
Labels: ready for review

#46 Scalar openAPI
  packages/server/package.json
  packages/server/src/base/base-app.tsx
  packages/server/src/base/type.ts
  packages/server/src/base/withOpenApi.ts
  packages/server/src/env/zod.ts
  packages/server/src/index.ts
  packages/server/src/routes/auth/auth.ts
  packages/server/src/routes/auth/index.test.ts
  packages/server/src/routes/auth/index.ts
  packages/server/src/routes/auth/login.ts
  packages/server/src/routes/auth/logout.ts
  packages/server/src/routes/auth/register.ts
  packages/server/src/routes/middleware/authentication.ts
  packages/server/src/routes/personal/index.ts
  packages/server/src/routes/personal/me.ts
  packages/server/src/routes/secret/routeTest.ts
  packages/server/src/routes/tests/environment.test.ts
  packages/server/src/routes/videos/index.ts
  packages/server/src/routes/videos/videos.ts
  packages/ui/src/domains/Marketing/Dashboard/Dashboard.tsx
  packages/ui/src/domains/Marketing/LandingPage/Header.tsx
  packages/ui/src/domains/Personal/Header.tsx
  packages/zod-types/process/index.ts
  yarn.lock
Labels: ready for review, reviewed
